# Generated by Django 3.2.16 on 2022-11-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('items', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('instruction_restaurant', models.TextField(null=True)),
                ('instruction_delivery', models.TextField(null=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('accept_rest', models.BooleanField(default=False)),
                ('accept_deli', models.BooleanField(default=False)),
                ('rest_id', models.IntegerField(default=-1)),
                ('deli_id', models.IntegerField(default=-1)),
            ],
        ),
    ]
