# Generated by Django 3.2.16 on 2022-11-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20221120_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prep_time',
            field=models.IntegerField(default=0),
        ),
    ]
