# Generated by Django 3.2.16 on 2022-12-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20221205_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.TextField()),
                ('order_id', models.IntegerField()),
                ('no_item', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('rest_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AlterField(
            model_name='order',
            name='instruction_delivery',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='instruction_restaurant',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
