# Generated by Django 3.2.16 on 2022-12-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_user_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='Contact_no',
            new_name='contact_no',
        ),
    ]
